apiVersion: v1
kind: ConfigMap
metadata:
  name: flaskapi-config
  namespace: ingress-nginx
data:
  MYSQL_DATABASE_USER: "root"
  MYSQL_DATABASE_PASSWORD: "root"
  MYSQL_DATABASE_DB: "BucketList"
  MYSQL_DATABASE_HOST: "mysql-service"
