# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service
#   namespace: ingress-nginx
# spec:
#   selector:
#     app: mysql
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306

apiVersion: v1
kind: Service
metadata:
  name: mysql-db-svc
  labels:
    app: mysql-db-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: db
  type: ClusterIP