# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mysql
#   namespace: ingress-nginx
# spec:
#   replicas: 1
#   # serviceName: mysql-service
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       # terminationGracePeriodSeconds: 10
#       containers:
#         - name: mysql
#           image: 422097883691.dkr.ecr.us-east-1.amazonaws.com/mysql-db:latest
#           ports:
#             - containerPort: 3306
#           envFrom:
#               - configMapRef:
#                   name: mysql-config
#           volumeMounts:
#             - name: mysql-persistent-storage
#               mountPath: /var/lib/mysql
#       volumes:
#         - name: mysql-persistent-storage
#           persistentVolumeClaim:
#             claimName: mysql-pv-claim 
  
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: 422097883691.dkr.ecr.us-east-1.amazonaws.com/mysql-db:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: db_root_password
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
    